### ISSUE TITLE
Can't use the Enter Key to add a new paragraph

### ISSUE THREAD

**Issue by goaround** [multidots/gutenberg_commenting#23]
Hi,

I can't use the Enter Key to add a new paragraph/block inside the Block Editor if the Plugin is enabled.

**Comment by poojabhimani12** [comment]
Hello,

May I know in which browser you are facing this issue?

**Comment by goaround** [comment]
Hi,

Firefox. Chrome works for me fine.

**Comment by lkraav** [comment]
> We have fixed this issue in the plugin's latest version. Please update latest version.

Hi team. It would be useful to take advantage of GH verbs in commit messages, so followers could better understand how and where something was fixed, as shown in https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue
