### ISSUE TITLE
Comments Panel always visible

### ISSUE THREAD

**Issue by goaround** [multidots/gutenberg_commenting#6]
Hi,

First: great plugin! I hope this functionality will be in core one time. 

I have version 1.0.1 installed and always see the Comments Panel even when there are no comments or the comment panel is not active.

I don't see this behaver in the demo but on two of my live sites and on my test site. 

![grafik](https://user-images.githubusercontent.com/5927337/99911764-d8742780-2cf6-11eb-8262-7008872aa706.png)

**Comment by poojabhimani12** [comment]
Hello Goaround ,

Hope you have updated Multicollab latest version. We have fixed this issue in our latest version. If you could not update the latest version then I request you please update it and feel free to contact us if anything is not working as your expectation.


Thanks,
Pooja

**Comment by goaround** [comment]
Hi @poojabhimani12 

Its now better (there is an option to hide the panel) but it's still always active even if there is no comment yet. I think the panel should only be visible by default e.g. on a new post, if there is at least one unresolved comment. 

The next problem is, if the panel is hidden, you set the `max-/width: 100% !important;` That overrides my theme `max-width: 872px` which fits the content on the front end and is important for me. 

![grafik](https://user-images.githubusercontent.com/5927337/120192208-2d9b7380-c21b-11eb-9561-d484e806d9e0.png)

I've removed the `max-/width: 100% !important;` from your CSS, and it works fine for me.

**Comment by poojabhimani12** [comment]
Hello @goaround

We Appreciate your valuable feedback and will fix it in the next release.

Thanks,
Pooja

**Comment by poojabhimani12** [comment]
Hello @goaround 

We have released the latest version of this plugin so I request you to please update the version and let me know if anything. Now your theme classes are not overrides.

Thanks,
Pooja

**Comment by goaround** [comment]
@poojabhimani12 looks better!

Would it be possible to remove the `max-/width: 100% !important;` from `.commentOn .editor-styles-wrapper .wp-block`, too? Then it would prefer always my theme style.

**Comment by poojabhimani12** [comment]
Hello @goaround 

Thanks for the Feedback. It will encourage us to make our plugin stable. 

".commentOn .editor-styles-wrapper .wp-block" will work only when you have given any comments on page/post so it would not affect your theme style. In the next release will surely keep in mind to avoid "!important" in our plugin CSS classes. 


Thanks,
Pooja
