### ISSUE TITLE
Could the meta tags be hidden?

### ISSUE THREAD

**Issue by chriscoyier** [multidots/gutenberg_commenting#8]
We make quite a bit of use of custom meta fields on CSS-Tricks, and now every single post has extra meta fields that I don't really know what are for and don't really wanna see:

<img width="966" alt="Screen Shot 2020-12-11 at 10 07 48 AM" src="https://user-images.githubusercontent.com/69156/101938860-f10a8b80-3b98-11eb-9ae0-0b470d764735.png">

(The quote is ours, the other two are not.)

Can't internally-used meta fields start with an underscore or something so authors don't need to see them?

**Comment by robicse11127** [comment]
Thanks for you concern. This has been fixed in v1.2.0
